### ISSUE TITLE
core-js-compat 3.4.6 published in a broken state

### ISSUE THREAD

**Issue by contra** [zloirock/core-js#710]
Seems like this just got published 15 minutes ago so I guess I'm the first one seeing it.

core-js compat 3.4.6 tries to load `./src/data` in helpers.js which is a file not published to NPM. I think it should be trying to load `./data` instead, which is present in the dist.

**Comment by zloirock** [comment]
Oops... Sorry.

**Comment by contra** [comment]
Issue was introduced here for reference: https://github.com/zloirock/core-js/commit/ec33d92fd293f8598d774424be49f46d4d1ff0d3#diff-2f5be9ba93f74ccd0b5583a510e92b15

**Comment by joamag** [comment]
@contra I'm also getting this issue, the package is broken here https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/helpers.js#L3

**Comment by zloirock** [comment]
Fixed, published.

**Comment by contra** [comment]
@zloirock Thanks!

**Comment by joamag** [comment]
I believe the build failed... https://travis-ci.org/zloirock/core-js/builds/619741722

**Comment by zloirock** [comment]
@joamag it's a fast fix only for the package since `./data` is missed on CI.

**Comment by contra** [comment]
Possibly a caching issue but I'm still getting 3.4.6 on all fresh installs, and the NPM website still shows 3.4.6 as the latest as well.

**Comment by bkoltai** [comment]
Can you please re-open this issue until the build passes?

**Comment by zloirock** [comment]
@bkoltai why?

**Comment by contra** [comment]
The version is live on NPM if you query the API directly but the tarball isn't served via upgrade or install - seems to be a caching issue on their end, been waiting for over an hour and it still isn't showing up. It did just appear on the website though so at least something is moving.

**Comment by nicolo-ribaudo** [comment]
Ref - https://github.com/npm/cli/issues/545
Please :+1: that issue.

**Comment by dcwarwick** [comment]
The caching thing is hitting a lot of people, unfortunately :-/ I still get 3.4.6 from `npm update` although `npm dist-tags` reports that latest=3.4.7. There's a bunch of questions hitting stack-overflow from people using Vue, React, etc.

**Comment by MayhemYDG** [comment]
It's fixed now, I'm getting the latest version from npm. I'm in London fwiw.

**Comment by bendemboski** [comment]
Ditto, in Seattle

**Comment by DerAzubi** [comment]
thanks for the update. searched for solution for 2h :D
